name: example-servant-elm

dependencies:
  - base
  - warp
  - aeson
  - servant
  - servant-elm
  - elm-bridge
  - wai
  - servant-server
  - text
  - transformers
  - containers
  - wai-app-static

internal-libraries:
  api:
    source-dirs:
      - server/src
    exposed-modules: Api
    other-modules: []

executables:
  server:
    main: Main.hs
    source-dirs:
      - server/src
    dependencies: api
    other-modules: [App]
  generate-elm:
    main: GenerateElm.hs
    source-dirs:
      - client/
    dependencies: api
    other-modules: []

tests:
  spec:
    main: Spec.hs
    build-tools:
      - hspec-discover
    source-dirs:
      - server/test
      - server/src
    dependencies:
      - warp >= 3.2.3
      - hspec
      - servant-client
      - http-client
      - http-types
    other-modules: [AppSpec, Api, App]
